/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_4_5

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun <T> List<T>.head(): T =
        if (this.isEmpty())
            throw IllegalArgumentException("head called on empty list")
        else
            this[0]

fun <T> List<T>.tail(): List<T> =
        if (this.isEmpty())
            throw IllegalArgumentException("tail called on empty list")
        else
            this.drop(1)





fun <T, U> foldLeft(list: List<T>, z: U, f: (U, T) -> U): U {
    tailrec fun foldLeft(list: List<T>, acc: U): U =
            if (list.isEmpty())
                acc
            else
                foldLeft(list.tail(), f(acc, list.head()))
    return foldLeft(list, z)
}

fun sum(list: List<Int>) =
	foldLeft(list, 0, Int::plus)

fun string(list: List<Char>) =
	foldLeft(list, "", String::plus)

fun <T> makeString(list: List<T>, delim: String) =
    foldLeft(list, "") { s, t -> if (s.isEmpty()) "$t" else "$s$delim$t" }



fun main() {
    println(App().greeting)
	println(sum(listOf(1,2,3,4,5)))
	println(string(listOf('a','b','c','d','e')))
	println(makeString(listOf(1,2,3,4,5),"+"))
	
}
